name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "joaomatheuslamao9@gmail.com"
          git config --global user.name "JoaoMatheusLamao"

      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
      - name: Create Tag
        run: |
          git tag -a v1.0 -m "Version 1.0"
          git push origin v1.0
