name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          git tag -a v1.0 -m "Version 1.0"
          git push origin v1.0
